baseURL = "https://example.edu"
languageCode = "en-us"

theme = "avicenna"
googleAnalytics = "UA-1234-6"
timeout=3000



[[params.introduction.paragraph]]
  text="""
  <font size="6" color="00008b"><Center>**Bryan J Lopez**</Center></font> </span>
  <Center>**Millikan High School**</Center>
<Center>1515 Hughes Way, Long Beach</Center>
<Center>CLASS OF 2020</Center>
<Center>BryanJLopez2020@gmail.com </Center>
<Center>http://BryanLopez.Netlify.com </Center>
<Center>562-240-4763</Center><br />
<br />
<font size="4">**GOAL**:</font> <font size="3">*To obtain a Bachelors Degree in Business and play soccer at the collegiate level.*</font>

<u><font size="4" color="00008b">**Student/Athlete Profile**</font></u>

**Height:** 6'1 **Weight:** 170lb

**Birthday:** 06/23/2002

**Dominant Foot:** Right

**Position:** Defense

**NCAA ID#** 1908663301

<u><font size="4" color="00008b">**ATHLETETICS**</font></u>

<font size="5">**Club Soccer**</font>
<br><pre class="tab">Coach Name:Hugo Sanchez   <u>hugojsanchez@gmail.com</u>    562-230-1466 </pre>

<pre class="tab">2018- 2019  **Long Beach Pateadores** Soccer club Champions League, Center Back

   """


